# -*- coding: utf-8 -*-
"""Tarea1-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NWUFTRla3jU_uD620SOsQwY2sh1CE2B
"""

import pandas as pd

df_ventas = pd.read_csv('ventas.csv')

print(df_ventas.columns)

ventas_por_categoria = df_ventas.groupby('Producto')['Cantidad'].sum().reset_index()
print("Cantidad total de productos vendidos por categoría:")
print(ventas_por_categoria)

df_ventas['TotalVentaProducto'] = df_ventas['Cantidad'] * df_ventas['Precio_Unitario']

ventas_totales_por_producto = df_ventas.groupby('Producto')['TotalVentaProducto'].sum().reset_index()

producto_mayor_venta = ventas_totales_por_producto.loc[ventas_totales_por_producto['TotalVentaProducto'].idxmax()]
print("\nProducto con el mayor total de ventas:")
print(producto_mayor_venta)


precio_promedio = df_ventas.groupby('Producto')['Precio_Unitario'].mean()
print("\nPrecio promedio de los productos vendidos:")
precio_promedio

"""Analisis del Clima"""

df_clima = pd.read_csv('clima.csv')
print(df_clima.columns)


temp_prom_ciudad= df_clima.groupby('Ciudad')['Temperatura'].mean().reset_index()
print("Temperatura promedio por ciudad:")
print(temp_prom_ciudad)

temp_max_ciudad = df_clima['Temperatura'].max()
print("Registro con la temperatura más alta:")
print(temp_max_ciudad)

temp_min_ciudad = df_clima['Temperatura'].min()
print("Registro con la temperatura más baja:")
print(temp_min_ciudad)

indice_max = df_clima['Temperatura'].idxmax()
ciudad_max = df_clima.loc[indice_max, 'Ciudad']
temp_max = df_clima.loc[indice_max, 'Temperatura']


indice_min = df_clima['Temperatura'].idxmin()
ciudad_min = df_clima.loc[indice_min, 'Ciudad']
temp_min = df_clima.loc[indice_min, 'Temperatura']

print(f"La ciudad con la temperatura más alta es {ciudad_max} con {temp_max}")
print(f"La ciudad con la temperatura más baja es {ciudad_min} con {temp_min}")

masde30= df_clima['Temperatura']>30

cant= masde30.sum()

print(cant)

conteo = df_clima.groupby('Ciudad')['Fecha'].count()
print(conteo.sum())

